In [1]:
import numpy as np
from tqdm import tqdm
from beta_update import BetaUpdate
import json
import math
from utils import generate_structures

In [2]:
structure_judgs = open('inferred_structure/exp_1_cond_2_no_struct.txt')
structure_judgs = json.load(structure_judgs)
n_agents = 3
structures = generate_structures(n_agents) 

In [4]:
average_matrix = np.zeros((3,3))
for k, v in enumerate(structure_judgs):
    probs = structure_judgs[str(k)]['9']
    for prob, struct in zip(probs, structures):
        average_matrix += struct * 1/50 * prob
print(average_matrix)

[[0.        0.5077786 0.0974242]
 [0.9999996 0.        0.0282092]
 [0.9999996 0.2119146 0.       ]]


In [6]:
structure_judgs = open('inferred_structure/exp_3_cond_1_independent.txt')
structure_judgs = json.load(structure_judgs)
n_agents = 3
structures = generate_structures(n_agents) 

In [7]:
average_matrix = np.zeros((3,3))
for k, v in enumerate(structure_judgs):
    probs = structure_judgs[str(k)]['9']
    for prob, struct in zip(probs, structures):
        average_matrix += struct * 1/22 * prob
    
print(average_matrix)

[[0.         0.33149409 0.30850045]
 [0.999995   0.         0.314705  ]
 [0.999995   0.14972182 0.        ]]


In [8]:
structure_judgs = open('inferred_structure/exp_3_cond_2_b_c.txt')
structure_judgs = json.load(structure_judgs)
n_agents = 3
structures = generate_structures(n_agents) 

average_matrix = np.zeros((3,3))
for k, v in enumerate(structure_judgs):
    probs = structure_judgs[str(k)]['9']
    for prob, struct in zip(probs, structures):
        average_matrix += struct * 1/21 * prob
    
print(average_matrix)

[[0.         0.29119952 0.41993238]
 [1.00000571 0.         0.59592667]
 [1.00000571 0.35071    0.        ]]
